import { Injectable } from '@angular/core';
import { Agent } from '../model/Agent';
import { Select2Model } from '../model/Select2Model';

@Injectable({
  providedIn: 'root',
})
export class Dao {
  public agent: Agent = {
    agentId: 'jshardlow',
    firstName: 'Jeff',
    lastName: 'Shardlow',
    fullName: 'Jeff Shardlow',
    email: 'jshardlow@utah.gov',
    image: '',
    address: '',
    city: '',
    state: '',
    zip: '',
    supervisorId: 'kchunt',
    myCaseload: ([] = [
      {
        ofndrNum: 1,
        firstName: 'Yogi',
        lastName: 'Bear',
        image: '',
        address: '123 Main St.',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '',
        phone: '',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 2,
        firstName: 'Papa',
        lastName: 'Smurf',
        image: '',
        address: '234 Main St.',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '84101',
        phone: '801-123-4567',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 3,
        firstName: 'Sneezy',
        lastName: 'Dwarf',
        image: '',
        address: '345 Center St.',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '84101',
        phone: '801-234-5678',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 4,
        firstName: 'Sleepy',
        lastName: 'Dwarf',
        image: '',
        address: '1234 West Temple',
        city: 'South Salt Lake City',
        state: 'UT',
        zip: '84115',
        phone: '385-345-6789',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 5,
        firstName: 'Smurfette',
        lastName: 'Smurf',
        image: '',
        address: '9212 700 E.',
        city: 'Magna',
        state: 'UT',
        zip: '84111',
        phone: '385-456-7890',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 6,
        firstName: 'Dopey',
        lastName: 'Dwarf',
        image: '',
        address: '67 American Ave.',
        city: 'Murray',
        state: 'UT',
        zip: '84123',
        phone: '435-567-8901',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 7,
        firstName: 'Grumpy',
        lastName: 'Dwarf',
        image: '',
        address: '12324 Minuteman Dr.',
        city: 'Draper',
        state: 'UT',
        zip: '84044',
        phone: '385-678-9012',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 8,
        firstName: 'Bashful',
        lastName: 'Dwarf',
        image: '',
        address: '8523 Redwood Rd.',
        city: 'South Jordan',
        state: 'UT',
        zip: '84088',
        phone: '435-789-0123',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 9,
        firstName: 'Happy',
        lastName: 'Dwarf',
        image: '',
        address: '735 500W',
        city: 'Moab',
        state: 'UT',
        zip: '84452',
        phone: '801-890-1234',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 10,
        firstName: 'Snow',
        lastName: 'White',
        image: '',
        address: '345 State St.',
        city: 'Logan',
        state: 'UT',
        zip: '84567',
        phone: '435-901-2345',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
    ]),
    otherOffenders: ([] = [
      {
        ofndrNum: 1,
        firstName: 'Yogi',
        lastName: 'Bear',
        image: '',
        address: '123 Main St.',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '',
        phone: '',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 2,
        firstName: 'Papa',
        lastName: 'Smurf',
        image: '',
        address: '234 Main St.',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '84101',
        phone: '801-123-4567',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 3,
        firstName: 'Sneezy',
        lastName: 'Dwarf',
        image: '',
        address: '345 Center St.',
        city: 'Salt Lake City',
        state: 'UT',
        zip: '84101',
        phone: '801-234-5678',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 4,
        firstName: 'Sleepy',
        lastName: 'Dwarf',
        image: '',
        address: '1234 West Temple',
        city: 'South Salt Lake City',
        state: 'UT',
        zip: '84115',
        phone: '385-345-6789',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 5,
        firstName: 'Smurfette',
        lastName: 'Smurf',
        image: '',
        address: '9212 700 E.',
        city: 'Magna',
        state: 'UT',
        zip: '84111',
        phone: '385-456-7890',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 6,
        firstName: 'Dopey',
        lastName: 'Dwarf',
        image: '',
        address: '67 American Ave.',
        city: 'Murray',
        state: 'UT',
        zip: '84123',
        phone: '435-567-8901',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 7,
        firstName: 'Grumpy',
        lastName: 'Dwarf',
        image: '',
        address: '12324 Minuteman Dr.',
        city: 'Draper',
        state: 'UT',
        zip: '84044',
        phone: '385-678-9012',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 8,
        firstName: 'Bashful',
        lastName: 'Dwarf',
        image: '',
        address: '8523 Redwood Rd.',
        city: 'South Jordan',
        state: 'UT',
        zip: '84088',
        phone: '435-789-0123',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 9,
        firstName: 'Happy',
        lastName: 'Dwarf',
        image: '',
        address: '735 500W',
        city: 'Moab',
        state: 'UT',
        zip: '84452',
        phone: '801-890-1234',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
      {
        ofndrNum: 10,
        firstName: 'Snow',
        lastName: 'White',
        image: '',
        address: '345 State St.',
        city: 'Logan',
        state: 'UT',
        zip: '84567',
        phone: '435-901-2345',
        lastSuccessfulContactDate: new Date(),
        contactArray: [],
      },
    ]),
  };

  public officerList: Agent[] = [
    {
      agentId: 'kchunt',
      firstName: 'Kurt',
      lastName: 'Hunt',
      fullName: 'Kurt Hunt',
      email: 'kchunt@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlow',
      myCaseload: ([] = []),
      otherOffenders: ([] = []),
    },
    {
      agentId: 'jshardlow',
      firstName: 'Jeff',
      lastName: 'Shardlow',
      fullName: 'Jeff Shardlow',
      email: 'jshardlow@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'kchunt',
      myCaseload: ([] = []),
      otherOffenders: ([] = []),
    },
    {
      agentId: 'mromney',
      firstName: 'Matt',
      lastName: 'Romney',
      fullName: 'Matt Romney',
      email: 'mromney@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlow',
      myCaseload: ([] = []),
      otherOffenders: ([] = []),
    },
    {
      agentId: 'tjones',
      firstName: 'Tess',
      lastName: 'Jones',
      fullName: 'Tess Jones',
      email: 'tjones@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlow',
      myCaseload: ([] = []),
      otherOffenders: ([] = []),
    },
    {
      agentId: 'jules',
      firstName: 'Jules',
      lastName: 'Hill',
      fullName: 'Jules Hill',
      email: 'jules@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlow',
      myCaseload: ([] = []),
      otherOffenders: ([] = []),
    },
    {
      agentId: 'hicks',
      firstName: 'John',
      lastName: 'Hicks',
      fullName: 'John Hicks',
      email: 'hicks@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlow',
      myCaseload: ([] = []),
      otherOffenders: ([] = []),
    },
  ];

  public contactTypeList: Select2Model[] = [
    { id: '10', text: 'COURT/BOARD DOC'},
    { id: '11', text: 'IPO/TRANSTN SUMMARY'},
    { id: '12', text: 'OPENING SUMMARY'},
    { id: '13', text: 'FINANCIAL'},
    { id: '15', text: 'COMPACT STATE'},
    { id: '16', text: 'SEX OFFENDER REGISTR'},
    { id: '17', text: 'TX/RESOURCE CENTER'},
    { id: '18', text: 'ASSESSMENT'},
    { id: '19', text: 'PRE-SUPERVISION NOTE'},
    { id: '20', text: 'FILE'},
    { id: '21', text: 'TRC CASE UPDATE'},
    { id: '22', text: 'TRC CLOSING SUMMARY'},
    { id: '23', text: 'DNA NOTES'},
    { id: '24', text: 'DIAGNOSTIC'},
    { id: '25', text: 'TRC EMPLOYMENT'},
    { id: '26', text: "WOMEN'S TRC"},
    { id: '27', text: 'WTRC CASE UPDATE'},
    { id: '28', text: 'WTRC CLOSING SUMMARY'},
    { id: '14', text: 'TRANSFER SUMMARY'},
    { id: '29', text: 'DORA 2-ASSESS & TX'},
    { id: '30', text: 'DORA 1-SCREEN ACCEPT'},
    { id: '32', text: 'DORA 4-HANDOFF'},
    { id: '33', text: 'DORA 5-TX REVIEW'},
    { id: '34', text: 'DORA 6-TERMINATION'},
    { id: '35', text: 'DORA 1-SCREEN DENIED'},
    { id: '36', text: 'DORA 2-ASSESS NO TX'},
    { id: '37', text: 'DORA 7-NO FUNDING'},
    { id: '38', text: 'TRC ENROLLMENT'},
    { id: '39', text: 'TRC TREATMENT REVIEW'},
    { id: '40', text: 'TX NOTE-GRAMA PROTEC'},
    { id: '48', text: 'DORA 7-DATA AUDIT'},
    { id: '49', text: 'DORA-8-TX FUND ENDED'},
    { id: '50', text: 'CAP REVIEW'},
    { id: '51', text: 'SUPERVISION REVIEW'},
    { id: '47', text: 'WTRC EMPLOYMENT'},
    { id: '52', text: 'WTRC ENROLLMENT'},
    { id: '53', text: 'WTRC TX REVIEW'},
    { id: '54', text: 'ORIENTATION'},
    { id: '55', text: 'AUDIT'},
    { id: '56', text: 'LEAVE'},
    { id: '57', text: 'SPECIAL REQUEST'},
    { id: '58', text: 'SUPPORT STAFF'},
    { id: '70', text: 'PATR SCREEN ACCEPT'},
    { id: '71', text: 'PATR SCREEN DENY'},
    { id: '75', text: 'VIVITROL SCREEN ACCE'},
    { id: '76', text: 'VIVITROL SCREEN DENY'},
    { id: '101', text: 'CACHE EVAL SCHEDULED'},
    { id: '102', text: 'CACHE EVAL COMPLETED'},
    { id: '72', text: 'TRC CLASS REMOVAL'},
    { id: '103', text: 'ORIENTATION W/FAM'},
    { id: '104', text: 'ORIENTATION W/O FAM'},
    { id: '105', text: 'REACH-SCREEN ACCEPT'},
    { id: '106', text: 'REACH-SCREEN DENIED'},
    { id: '80', text: 'DATA CLEANUP'},
    { id: '98', text: 'ADDRESS VERIFICATION'},
    { id: '107', text: 'CCC CLOSING SUMMARY'},
    { id: '78', text: 'LOW ELECTRONIC CHECK'},
    { id: '108', text: 'GPS/ELECTRONIC MONIT'},
    { id: '109', text: 'UCI/REENTRY'},
    { id: '111', text: 'CCC REFERRAL'},
    { id: '77', text: 'FUGITIVE UPDATE'},
    { id: '112', text: 'NOTARY'},
    { id: '113', text: 'REENTRY/TRANSITION'},
    { id: '114', text: 'PROGRESS NOTE PD'},
    { id: '115', text: 'EMPLOY APPLICATION'},
    { id: '116', text: 'BCI'},
  ];
  public locationList: Select2Model[] = [
    { id: '1', text: 'OFFICE'},
    { id: '2', text: 'RESIDENCE'},
    { id: '3', text: 'EMPLOYMENT'},
    { id: '4', text: 'COMMUNITY CORRECTION CENTER'},
    { id: '5', text: 'COMMUNITY SERVICE SITE'},
    { id: '6', text: 'COURT'},
    { id: '7', text: 'TX/RESOURCE CENTER'},
    { id: '8', text: 'OTHER RESIDENCE'},
    { id: '9', text: 'FIELD'},
    { id: '10', text: 'TREATMENT PROVIDER'},
    { id: '11', text: 'JAIL'},
    { id: '12', text: 'CRIME SCENE'},
    { id: '13', text: 'LAW ENFORCEMENT AGENCY'},
    { id: '14', text: 'OTHER'},
    { id: '15', text: 'FAMILY'},
    { id: '16', text: 'ASSOCIATE'},
    { id: '17', text: 'BOARD OF PARDONS/PAROLE'},
    { id: '18', text: 'COMPACT STATE'},
    { id: '19', text: 'VICTIM'},
    { id: '20', text: 'PRISON'},
    { id: '21', text: 'NOT APPLICABLE'},
    { id: '22', text: 'OTHER AGENCY'},
    { id: '25', text: 'EMPLOYMENT COORDINATOR'},
    { id: '26', text: 'UDOCA'},
    { id: '27', text: 'HOMELESS/OTHER SERVICES'},
  ];
  

  constructor() {}
}
