import { Injectable } from '@angular/core';
import { Agent } from '../model/Agent';
import { Select2Model } from '../model/Select2Model';
import { Offender } from '../model/Offender';
import { OffenderBase } from '../model/OffenderBase';

@Injectable({
  providedIn: 'root',
})
export class Dao {
  public agent: Agent = {
    userId: 'jshardlo',
    agentId: 'jshardlo',
    firstName: 'Jeff',
    lastName: 'Shardlow',
    fullName: 'Jeff Shardlow',
    agentEmail: 'jshardlo@utah.gov',
    image: '',
    address: '',
    city: '',
    state: '',
    zip: '',
    supervisorId: 'kchunt',
    ofndrNumList: ([] = []),
  };

  public otherOffenders: Offender[] = [
    {
      offenderNumber: 21,
      defaultOffenderName: {
        firstName: 'Yogli',
        lastName: 'Beary',
      },
      birthDate: new Date('1980-01-01'),
      agentId: 'mromney',
      image: '',
      address: '1234 Main St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84115',
      phone: '801-123-4567',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
  ];

  //self explanatory
  public myCaseload: Offender[] = [
    {
      offenderNumber: 1,
      defaultOffenderName: {
        firstName: 'Yogi',
        lastName: 'Bear',
      },
      birthDate: new Date('1980-01-01'),
      agentId: 'jshardlo',
      image: '',
      address: '123 Main St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '',
      phone: '',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 2,
      defaultOffenderName: {
        firstName: 'Papa',
        lastName: 'Smurf',
      },
      birthDate: new Date('1975-02-02'),
      agentId: 'jshardlo',
      image: '',
      address: '234 Main St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84101',
      phone: '801-123-4567',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 3,
      defaultOffenderName: {
        firstName: 'Sneezy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1985-03-03'),
      agentId: 'jshardlo',
      image: '',
      address: '345 Center St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84101',
      phone: '801-234-5678',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 4,
      defaultOffenderName: {
        firstName: 'Sleepy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1986-04-04'),
      agentId: 'jshardlo',
      image: '',
      address: '1234 West Temple',
      city: 'South Salt Lake City',
      state: 'UT',
      zip: '84115',
      phone: '385-345-6789',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 5,
      defaultOffenderName: {
        firstName: 'Smurfette',
        lastName: 'Smurf',
      },
      birthDate: new Date('1992-05-05'),
      agentId: 'jshardlo',
      image: '',
      address: '9212 700 E.',
      city: 'Magna',
      state: 'UT',
      zip: '84111',
      phone: '385-456-7890',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 6,
      defaultOffenderName: {
        firstName: 'Dopey',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1987-06-06'),
      agentId: 'jshardlo',
      image: '',
      address: '67 American Ave.',
      city: 'Murray',
      state: 'UT',
      zip: '84123',
      phone: '435-567-8901',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 7,
      defaultOffenderName: {
        firstName: 'Grumpy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1988-07-07'),
      agentId: 'jshardlo',
      image: '',
      address: '12324 Minuteman Dr.',
      city: 'Draper',
      state: 'UT',
      zip: '84044',
      phone: '385-678-9012',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 8,
      defaultOffenderName: {
        firstName: 'Bashful',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1989-08-08'),
      agentId: 'jshardlo',
      image: '',
      address: '8523 Redwood Rd.',
      city: 'South Jordan',
      state: 'UT',
      zip: '84088',
      phone: '435-789-0123',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 9,
      defaultOffenderName: {
        firstName: 'Happy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1991-09-09'),
      agentId: 'jshardlo',
      image: '',
      address: '735 500W',
      city: 'Moab',
      state: 'UT',
      zip: '84452',
      phone: '801-890-1234',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 10,
      defaultOffenderName: {
        firstName: 'Snow',
        lastName: 'White',
      },
      birthDate: new Date('1990-01-01'),
      agentId: 'jshardlo',
      image: '',
      address: '345 State St.',
      city: 'Logan',
      state: 'UT',
      zip: '84567',
      phone: '435-901-2345',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      nextScheduledContactDate: new Date(),
    },
  ];

  //basic offender info for all other offenders in AP&P program
  public allOtherOffenders: OffenderBase[] = [
    {
      offenderNumber: 11,
      defaultOffenderName: {
        firstName: 'Yogi',
        lastName: 'Bear',
      },
      birthDate: new Date('1980-01-01'),
      agentId: 'kchunt',
    },
    {
      offenderNumber: 12,
      defaultOffenderName: {
        firstName: 'Papa',
        lastName: 'Smurf',
      },
      birthDate: new Date('1975-02-02'),
      agentId: 'mromney',
    },
    {
      offenderNumber: 13,
      defaultOffenderName: {
        firstName: 'Sneezy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1985-03-03'),
      agentId: 'kchunt',
    },
    {
      offenderNumber: 14,
      defaultOffenderName: {
        firstName: 'Sleepy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1986-04-04'),
      agentId: 'mromney',
    },
    {
      offenderNumber: 15,
      defaultOffenderName: {
        firstName: 'Smurfette',
        lastName: 'Smurf',
      },
      birthDate: new Date('1992-05-05'),
      agentId: 'kchunt',
    },
    {
      offenderNumber: 16,
      defaultOffenderName: {
        firstName: 'Dopey',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1987-06-06'),
      agentId: 'tjones',
    },
    {
      offenderNumber: 17,
      defaultOffenderName: {
        firstName: 'Grumpy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1988-07-07'),
      agentId: 'tjones',
    },
    {
      offenderNumber: 18,
      defaultOffenderName: {
        firstName: 'Bashful',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1989-08-08'),
      agentId: 'tjones',
    },
    {
      offenderNumber: 19,
      defaultOffenderName: {
        firstName: 'Happy',
        lastName: 'Dwarf',
      },
      birthDate: new Date('1991-09-09'),
      agentId: 'mromney',
    },
    {
      offenderNumber: 20,
      defaultOffenderName: {
        firstName: 'Snow',
        lastName: 'White',
      },
      birthDate: new Date('1990-01-01'),
      agentId: 'mromney',
    },
  ];

  public allOtherOffendersWithContactInfo: Offender[] = [
    {
      offenderNumber: 11,
      defaultOffenderName: {
        firstName: 'Yogi',
        lastName: 'Bear',
      },
      agentId: 'jshardlo',
      image: '',
      address: '123 Main St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '',
      phone: '',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1980-01-01'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 12,
      defaultOffenderName: {
        firstName: 'Papa',
        lastName: 'Smurf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '234 Main St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84101',
      phone: '801-123-4567',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1975-02-02'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 13,
      defaultOffenderName: {
        firstName: 'Sneezy',
        lastName: 'Dwarf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '345 Center St.',
      city: 'Salt Lake City',
      state: 'UT',
      zip: '84101',
      phone: '801-234-5678',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1985-03-03'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 14,
      defaultOffenderName: {
        firstName: 'Sleepy',
        lastName: 'Dwarf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '1234 West Temple',
      city: 'South Salt Lake City',
      state: 'UT',
      zip: '84115',
      phone: '385-345-6789',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1986-04-04'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 15,
      defaultOffenderName: {
        firstName: 'Smurfette',
        lastName: 'Smurf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '9212 700 E.',
      city: 'Magna',
      state: 'UT',
      zip: '84111',
      phone: '385-456-7890',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1992-05-05'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 16,
      defaultOffenderName: {
        firstName: 'Dopey',
        lastName: 'Dwarf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '67 American Ave.',
      city: 'Murray',
      state: 'UT',
      zip: '84123',
      phone: '435-567-8901',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1987-06-06'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 17,
      defaultOffenderName: {
        firstName: 'Grumpy',
        lastName: 'Dwarf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '12324 Minuteman Dr.',
      city: 'Draper',
      state: 'UT',
      zip: '84044',
      phone: '385-678-9012',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1988-07-07'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 18,
      defaultOffenderName: {
        firstName: 'Bashful',
        lastName: 'Dwarf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '8523 Redwood Rd.',
      city: 'South Jordan',
      state: 'UT',
      zip: '84088',
      phone: '435-789-0123',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1989-08-08'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 19,
      defaultOffenderName: {
        firstName: 'Happy',
        lastName: 'Dwarf',
      },
      agentId: 'jshardlo',
      image: '',
      address: '735 500W',
      city: 'Moab',
      state: 'UT',
      zip: '84452',
      phone: '801-890-1234',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1991-09-09'),
      nextScheduledContactDate: new Date(),
    },
    {
      offenderNumber: 20,
      defaultOffenderName: {
        firstName: 'Snow',
        lastName: 'White',
      },
      agentId: 'jshardlo',
      image: '',
      address: '345 State St.',
      city: 'Logan',
      state: 'UT',
      zip: '84567',
      phone: '435-901-2345',
      lastSuccessfulContactDate: new Date(),
      contactArray: [],
      birthDate: new Date('1990-01-01'),
      nextScheduledContactDate: new Date(),
    },
  ];

  public officerList: Agent[] = [
    {
      userId: '1',
      agentId: 'kchunt',
      firstName: 'Kurt',
      lastName: 'Hunt',
      fullName: 'Kurt Hunt',
      agentEmail: 'kchunt@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlo',
      ofndrNumList: ([] = []),
    },
    {
      userId: '2',
      agentId: 'jshardlo',
      firstName: 'Jeff',
      lastName: 'Shardlow',
      fullName: 'Jeff Shardlow',
      agentEmail: 'jshardlo@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'kchunt',
      ofndrNumList: ([] = []),
    },
    {
      userId: '3',
      agentId: 'mromney',
      firstName: 'Matt',
      lastName: 'Romney',
      fullName: 'Matt Romney',
      agentEmail: 'mromney@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlo',
      ofndrNumList: ([] = []),
    },
    {
      userId: '4',
      agentId: 'tjones',
      firstName: 'Tess',
      lastName: 'Jones',
      fullName: 'Tess Jones',
      agentEmail: 'tjones@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlo',
      ofndrNumList: ([] = []),
    },
    {
      userId: '5',
      agentId: 'jules',
      firstName: 'Jules',
      lastName: 'Hill',
      fullName: 'Jules Hill',
      agentEmail: 'jules@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlo',
      ofndrNumList: ([] = []),
    },
    {
      userId: '6',
      agentId: 'hicks',
      firstName: 'John',
      lastName: 'Hicks',
      fullName: 'John Hicks',
      agentEmail: 'hicks@utah.gov',
      image: '',
      address: '',
      city: '',
      state: '',
      zip: '',
      supervisorId: 'jshardlo',
      ofndrNumList: ([] = []),
    },
  ];

  public contactTypeList: Select2Model[] = [
    { id: 98, text: 'ADDRESS VERIFICATION' },
    { id: 8, text: 'CASE UPDATE' },
    { id: 77, text: 'FUGITIVE UPDATE' },
    { id: 108, text: 'GPS/ELECTRONIC MONIT' },
    { id: 1, text: 'OFFICE REPORT' },
    { id: 114, text: 'PROGRESS NOTE PD' },
    { id: 2, text: 'STAFF TO OFFENDER' },
    { id: 3, text: 'TELEPHONE' },
  ];
  public locationList: Select2Model[] = [
    { id: 1, text: 'OFFICE' },
    { id: 2, text: 'RESIDENCE' },
    { id: 3, text: 'EMPLOYMENT' },
    { id: 4, text: 'COMMUNITY CORRECTION CENTER' },
    { id: 5, text: 'COMMUNITY SERVICE SITE' },
    { id: 6, text: 'COURT' },
    { id: 7, text: 'TX/RESOURCE CENTER' },
    { id: 8, text: 'OTHER RESIDENCE' },
    { id: 9, text: 'FIELD' },
    { id: 10, text: 'TREATMENT PROVIDER' },
    { id: 11, text: 'JAIL' },
    { id: 12, text: 'CRIME SCENE' },
    { id: 13, text: 'LAW ENFORCEMENT AGENCY' },
    { id: 14, text: 'OTHER' },
    { id: 15, text: 'FAMILY' },
    { id: 16, text: 'ASSOCIATE' },
    { id: 17, text: 'BOARD OF PARDONS/PAROLE' },
    { id: 18, text: 'COMPACT STATE' },
    { id: 19, text: 'VICTIM' },
    { id: 20, text: 'PRISON' },
    { id: 21, text: 'NOT APPLICABLE' },
    { id: 22, text: 'OTHER AGENCY' },
    { id: 25, text: 'EMPLOYMENT COORDINATOR' },
    { id: 26, text: 'UDOCA' },
    { id: 27, text: 'HOMELESS/OTHER SERVICES' },
  ];

  constructor() {}
}
